# Generated by Django 4.2.1 on 2025-05-23 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mobile_store', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='status',
        ),
    ]
